version: "3.3"
services:
  postgres_kratos: #Postgres container for Kratos
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory
      POSTGRES_DB: kratos
    volumes:
      - /srv/docker/kratos_postgres:/var/lib/postgresql/data
    networks:
      - ory-internal
  postgres_hydra: #Postgres container for Hydra
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory
      POSTGRES_DB: hydra
    volumes:
      - /srv/docker/hydra_postgres:/var/lib/postgresql/data
    networks:
      - ory-internal
  kratos: #Kratos container
    depends_on:
      - postgres_kratos
    image: ghcr.io/spaceprojectnpo/ory-kratos:latest
    restart: always
    environment:
      # Postgres configuration
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory
      POSTGRES_DBNAME: kratos
      POSTGRES_HOST: postgres_kratos
      POSTGRES_PORT: 5432

      # Kratos configuration (by environment variables)
      ## serve.public.base_url (String)
      SERVE_PUBLIC_BASE_URL: https://accounts.${BASE_DOMAIN}/
      ## selfservice.default_browser_return_url (String)
      SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: https://accounts.${BASE_DOMAIN}/auth/
      ## selfservice.allowed_return_urls (Array)
      SELFSERVICE_ALLOWED_RETURN_URLS: "[https://accounts.${BASE_DOMAIN}/]"
      ## selfservice.flows.error_ui_url (String)
      SELFSERVICE_FLOW_ERROR_UI_URL: https://accounts.${BASE_DOMAIN}/auth/errors
      ## selfservice.flows.settings_ui_url (String)
      SELFSERVICE_FLOWS_SETTINGS_UI_URL: https://accounts.${BASE_DOMAIN}/auth/settings
      ## selfservice.flows.recovery_enabled (Boolean)
      SELFSERVICE_FLOWS_RECOVERY_ENABLED: "true"
      ## selfservice.flows.recovery_ui_url (String)
      SELFSERVICE_FLOWS_RECOVERY_UI_URL: https://accounts.${BASE_DOMAIN}/auth/recovery
      ## selfservice.flows.verification_enabled (Boolean)
      SELFSERVICE_FLOWS_VERIFICATION_ENABLED: "true"
      ## selfservice.flows.verification_ui_url (String)
      SELFSERVICE_FLOWS_VERIFICATION_UI_URL: https://accounts.${BASE_DOMAIN}/auth/verification
      ## selfservice.flows.verification.after.default_browser_return_url (String)
      SELFSERVICE_FLOWS_VERIFICATION_AFTER_DEFAULT_BROWSER_RETURN_URL: https://accounts.${BASE_DOMAIN}/auth/
      ## selfservice.flows.logout.after.default_browser_return_url (String)
      SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL: https://accounts.${BASE_DOMAIN}/auth/
      ## selfservice.flows.login.ui_url (String)
      SELFSERVICE_FLOWS_LOGIN_UI_URL: https://accounts.${BASE_DOMAIN}/auth/login
      ## selfservice.flows.login.lifespan (Duration)
      SELFSERVICE_FLOWS_LOGIN_LIFESPAN: 10m
      ## selfservice.flows.registration.ui_url (String)
      SELFSERVICE_FLOWS_REGISTRATION_UI_URL: https://accounts.${BASE_DOMAIN}/auth/registration
    networks:
      - ory-internal
    ports:
      - 4433:4433 # Public API port
      - 4434:4434 # Admin API port
  kratos_ui:
    depends_on:
      - kratos
    image: spaceproject/ory-kratos-ui:latest
    restart: always
    environment:
      # Kratos Public API
      KRATOS_PUBLIC_URL: http://kratos:4433
      # Proxied Public API
      KRATOS_BROWSER_URL: https://accounts.${BASE_DOMAIN}/ 
    networks:
      - ory
      - ory-internal
    ports:
      - 8443:3000 # Public UI port
  hydra:
    depends_on:
      - postgres_hydra
      - kratos
    image: ghcr.io/spaceprojectnpo/ory-hydra:latest
    ports:
      - 5444:4444 # Public API port
      - 5445:4445 # Admin API port
    restart: always
    environment:
      #Postgres configuration
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory
      POSTGRES_DBNAME: hydra
      POSTGRES_HOST: postgres_hydra
      POSTGRES_PORT: 5432

      # Hydra configuration (environment variables)
      URLS_SELF_ISSUER: https://accounts.${BASE_DOMAIN}/ 
      URLS_CONSENT: https://accounts.${BASE_DOMAIN}/auth/consent 
      URLS_LOGIN: https://accounts.${BASE_DOMAIN}/auth/login 

      # Secrets
      SECRETS_SYSTEM: ${HYDRA_SYSTEM_SECRET}
    networks:
      - ory-internal

networks:
  ory: # create a network for the public facing services
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.5.0/16"
  ory-internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.4.0/16"
#volumes:
#  kratos: #Volume for Kratos Postgres data, must be persistent
#    driver: local
#    driver_opts:
#      type: none
#      device: /srv/docker/kratos_postgres
#      o: bind
    
#  hydra: #Volume for Hydra Postgres data, must be persistent
#    driver: local
#    driver_opts:
#      type: none
#      device: /srv/docker/hydra_postgres
#      o: bind
