version: "3.3"
services:
  postgres_kratos: #Postgres container for Kratos
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory
      POSTGRES_DB: kratos
    volumes:
      - /srv/docker/kratos_postgres:/var/lib/postgresql/data
  postgres_hydra: #Postgres container for Hydra
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory
      POSTGRES_DB: hydra
    volumes:
      - /srv/docker/hydra_postgres:/var/lib/postgresql/data
  kratos: #Kratos container
    depends_on:
      - postgres_kratos
    image: ghcr.io/spaceprojectnpo/ory-kratos:latest
    restart: always
    links:
      - postgres_kratos:postgres_kratos
    ports:
      - "4433:4433"
      - "4434:4434"
    environment:
      # Postgres configuration
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory
      POSTGRES_DBNAME: kratos
      POSTGRES_HOST: postgres_kratos
      POSTGRES_PORT: 5432

      # Kratos configuration (by environment variables)
      ## serve.public.base_url (String)
      SERVE_PUBLIC_BASE_URL: https://accounts.${BASE_DOMAIN}/
      ## serve.public.cors.enabled (Boolean)
      SERVE_PUBLIC_CORS_ENABLED: "true"
      ## serve.admin.base_url (String)
      SERVE_ADMIN_BASE_URL: http://kratos:4434/
      ## selfservice.default_browser_return_url (String)
      SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: https://accounts.${BASE_DOMAIN}/auth/
      ## selfservice.allowed_return_urls (Array)
      SELFSERVICE_ALLOWED_RETURN_URLS: "[https://accounts.${BASE_DOMAIN}/]"
      ## selfservice.flows.error_ui_url (String)
      SELFSERVICE_FLOW_ERROR_UI_URL: https://accounts.${BASE_DOMAIN}/auth/errors
      ## selfservice.flows.settings_ui_url (String)
      SELFSERVICE_FLOWS_SETTINGS_UI_URL: https://accounts.${BASE_DOMAIN}/auth/settings
      ## selfservice.flows.recovery_enabled (Boolean)
      SELFSERVICE_FLOWS_RECOVERY_ENABLED: "true"
      ## selfservice.flows.recovery_ui_url (String)
      SELFSERVICE_FLOWS_RECOVERY_UI_URL: https://accounts.${BASE_DOMAIN}/auth/recovery
      ## selfservice.flows.verification_enabled (Boolean)
      SELFSERVICE_FLOWS_VERIFICATION_ENABLED: "true"
      ## selfservice.flows.verification_ui_url (String)
      SELFSERVICE_FLOWS_VERIFICATION_UI_URL: https://accounts.${BASE_DOMAIN}/auth/verification
      ## selfservice.flows.verification.after.default_browser_return_url (String)
      SELFSERVICE_FLOWS_VERIFICATION_AFTER_DEFAULT_BROWSER_RETURN_URL: https://accounts.${BASE_DOMAIN}/auth/
      ## selfservice.flows.logout.after.default_browser_return_url (String)
      SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL: https://accounts.${BASE_DOMAIN}/auth/
      ## selfservice.flows.login.ui_url (String)
      SELFSERVICE_FLOWS_LOGIN_UI_URL: https://accounts.${BASE_DOMAIN}/auth/login
      ## selfservice.flows.login.lifespan (Duration)
      SELFSERVICE_FLOWS_LOGIN_LIFESPAN: 10m
      ## selfservice.flows.registration.ui_url (String)
      SELFSERVICE_FLOWS_REGISTRATION_UI_URL: https://accounts.${BASE_DOMAIN}/auth/registration
      ## secrets.cookie (Array)
      SECRETS_COOKIE: ${KRATOS_COOKIE_SECRET}
      ## secrets.cipher (Array)
      SECRETS_CIPHER: ${KRATOS_CIPHER_SECRET}
      ## identity.default_schema_id (String)
      IDENTITY_DEFAULT_SCHEMA_ID: default
      ## identity.schemas (Array)
      IDENTITY_SCHEMAS: '[{"id":"default","url":"${KRATOS_IDENTITY_SCHEMA}"}]'
      ## courier.smtp.connection_uri (String)
      COURIER_SMTP_CONNECTION_URI: smtps://${SMTP_USER}:${SMTP_PASSWORD}@${SMTP_HOST}:${SMTP_PORT}/?skip_ssl_verify=true
    
  kratos_ui:
    depends_on:
      - kratos
    image: ghcr.io/spaceprojectnpo/ory-kratosui-custom:latest
    restart: always
    links:
      - kratos:kratos
    ports:
      - "9843:3000"
    networks:
      - ory
    environment:
      # Kratos Public API
      KRATOS_PUBLIC_URL: https://accounts.${BASE_DOMAIN}/api/admin/
      # Proxied Public API
      KRATOS_BROWSER_URL: https://accounts.${BASE_DOMAIN}/ 

  hydra:
    depends_on:
      - postgres_hydra
      - kratos
    image: ghcr.io/spaceprojectnpo/ory-hydra:latest
    links:
      - postgres_hydra:postgres_hydra
      - kratos:kratos
    ports:
      - "4444:4444"
      - "4445:4445"
    restart: always
    environment:
      #Postgres configuration
      POSTGRES_USER: ory
      POSTGRES_PASSWORD: ory
      POSTGRES_DBNAME: hydra
      POSTGRES_HOST: postgres_hydra
      POSTGRES_PORT: 5432

      # Hydra configuration (environment variables)
      URLS_SELF_ISSUER: https://accounts.${BASE_DOMAIN}/ 
      URLS_CONSENT: https://accounts.${BASE_DOMAIN}/auth/consent 
      URLS_LOGIN: https://accounts.${BASE_DOMAIN}/auth/login 

      # Secrets
      SECRETS_SYSTEM: ${HYDRA_SYSTEM_SECRET}

networks:
  ory: # create a network for the public facing services
    driver: bridge