# -----------------------
# NGINX Proxy for ORY Hydra Dockerfile
# Author: SpaceProject
# -----------------------

FROM nginx:latest

LABEL maintainer="SpaceProject <docker-images@our-space.xyz>"

#Install crontab
RUN apt-get update && apt-get install -y cron && apt-get clean
# Copy nginx file
COPY ./nginx/ory-oauth.conf.template /etc/nginx/templates/ory-oauth.conf.template
# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy entrypoint
COPY ./pre-entrypoint.sh /pre-entrypoint.sh
RUN chmod +x /pre-entrypoint.sh

ENTRYPOINT ["/pre-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]