# -----------------------
# NGINX Proxy for ORY { Kratos, Hydra, Kratos-UI } Dockerfile
# Author: SpaceProject
# -----------------------

FROM nginx:latest

LABEL maintainer="SpaceProject <docker-images@our-space.xyz>"

# Copy nginx files
COPY ./nginx/ory.conf.template /etc/nginx/templates/ory.conf.template
# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy entrypoint
COPY ./pre-entrypoint.sh /pre-entrypoint.sh
RUN chmod +x /pre-entrypoint.sh

ENTRYPOINT ["/pre-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]