# -----------------------
# NGINX Proxy for ORY { Kratos, Hydra, Kratos-UI } Dockerfile
# Author: SpaceProject
# -----------------------

FROM nginx:latest

LABEL maintainer="SpaceProject <docker-images@our-space.xyz>"

# Copy nginx files
COPY ./nginx/ory-kratos-ui.conf.template /etc/nginx/templates/ory-kratos-ui.conf.template
COPY ./nginx/ory-kratos.conf.template /etc/nginx/templates/ory-kratos.conf.template

# Install dependencies
COPY ./install-certbot.sh /install-certbot.sh
RUN chmod +x /install-certbot.sh
RUN /install-certbot.sh && rm /install-certbot.sh

# Copy entrypoint
COPY ./pre-entrypoint.sh /pre-entrypoint.sh
RUN chmod +x /pre-entrypoint.sh

ENTRYPOINT ["/pre-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]