name: Build Ory Images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - hydra/**
      - kratos/**
jobs:
  build-push:
    name: "Build ${{ matrix.image }} image"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - hydra
          - kratos
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.image }}
          file: ./${{ matrix.image }}/dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/spaceprojectnpo/ory-${{ matrix.image }}:latest